name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Criar .env
      run: |
        echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env
        echo "BASE_URL_GRAPHQL=${{ secrets.BASE_URL_GRAPHQL }}" >> .env

    - name: Subir a API 
      run: npm start &
    
    - name: Esperar a API REST estar Funcionando
      run: sleep 5

    - name: Rodar os testes de API via Controller
      run: npm run test-controller

    - name: Rodar os testes de API via HTTP
      run: npm run test-external

    - name: Subir a API GRAPHQL
      run: npm run start-graphql &

    - name: Esperar a API GRAPHQL estar Funcionando
      run: sleep 5

    - name: Rodar os testes de API GRAPHQL
      run: npm run test-external-graphql

    - name: Rodar todos os testes API HTTP e GRAPHQL
      run: npm run test-all
